baseurl: https://frankchi.com
languageCode: zh-tw
theme: stack
paginate: 15
title: Frank 法蘭克
# Change it to your Disqus shortname before using
disqusShortname: hugo-theme-stack

# GA Tracking ID
googleAnalytics: G-G56GF8R508

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk
DefaultContentLanguage: zh-tw

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:
    footer:
        since: 2020
        customText: 由法蘭克自行維護～

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 
        subtitle: 看電影＊學英文
        social: 
        avatar:
            enabled: true
            local: true
            src: /img/frank_logo.png

    article:
        math: false
        toc: true
        readingTime: false
        license:
            enabled: true
            default: 

    comments:
        enabled: false
        provider: disqus

        disqusjs:
            shortname:
            apiUrl:
            apiKey:
            admin:
            adminLabel:

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/client.html
        waline:
            serverURL:
            lang:
            visitor:
            avatar:
            emoji:
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
            requiredMeta:
                - name
                - email
                - url
            placeholder:
            locale:
                admin: Admin

        twikoo:
            envId:
            region:
            path:
            lang:

        giscus:
            repo:
            repoID:
            category:
            categoryID:
            mapping:
            lightTheme:
            darkTheme:
            reactionsEnabled: 1
            emitMetadata: 0

        gitalk:
            owner: 
            admin:  
            repo: 
            clientID: 
            clientSecret: 
        
        cusdis:
            host: 
            id: 

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 15

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true

        content:
            enabled: true



### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: home
          name: 首頁
          url: /
          weight: -200
          params:
              ### For demonstration purpose, the home link will be open in a new tab
              newTab: false
              icon: icons8-home

        - identifier: class
          name: 找我學英文
          url: /class.html
          weight: -180
          params:
            icon: icons8-teaching
            newTab: false
            

        # - identifier: youtube
        #   name: Youtube頻道
        #   url: https://www.youtube.com/channel/UCWviCm7p7dnjmf37P2jpx4w
        #   weight: -175
        #   params:
        #     icon: icons8-youtube
        #     newTab: false


        # - identifier: tiktok
        #   name: Tiktok
        #   url: https://www.tiktok.com/@tobefrank0910
        #   weight: -170
        #   params:
        #       newTab: false
        #       icon: icons8-tiktok

        # - identifier: Facebook
        #   name: Facebook
        #   url: https://www.facebook.com/tobefrank7777/reels
        #   weight: -165
        #   params:
        #       newTab: false
        #       icon: icons8-facebook

        # - identifier: instagram
        #   name: Instagram
        #   url: https://www.instagram.com/tobefrank777/
        #   weight: -100
        #   params:
        #       newTab: false
        #       icon: icons8-instagram
    social:
        - identifier: facebook
          name: Facebook
          url: https://www.facebook.com/tobefrank7777/reels
          params:
              newTab: true
              icon: icons8-facebook

        - identifier: youtube
          name: Youtube
          url: https://www.youtube.com/channel/UCWviCm7p7dnjmf37P2jpx4w
          params:
              newTab: true
              icon: icons8-youtube

        - identifier: tiktok
          name: Tiktok
          url: https://www.tiktok.com/@tobefrank0910
          params:
              newTab: true
              icon: icons8-tiktok

        - identifier: instagram
          name: Instagram
          url: https://www.instagram.com/tobefrank777/
          params:
              newTab: true
              icon: icons8-instagram

            


related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
